name: Sync labels
on:
  workflow_dispatch:
    inputs:
      repository:
        description: "The repo to sync labels on"
        required: true
      token:
        description: "An alternative GitHub token to use instead"
        required: true
  push:
    branches:
      - main
    paths:
      - .github/labels.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: micnncim/action-label-syncer@v1
        if: ${{ github.event_name == 'push' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: micnncim/action-label-syncer@v1
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          repository: ${{ inputs.repository }}
          token: ${{ inputs.token }}
